name: Privateer CI Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mpi4py/setup-mpi@v1
      - name: Clone repo
        run: cd $GITHUB_WORKSPACE
      - name: Install Boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with: boost_version: 1.84.0
      - name: Build
        run: |
          mkdir build && cd build
          git clone https://github.com/facebook/zstd
          cmake -DZSTD_ROOT=zstd -DLIBZSTD=zstd/lib/zstd.h -DCMAKE_INSTALL_PREFIX=. ..
          make install
          make test
